# Generated by Django 2.0.1 on 2018-01-25 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='all_day',
            field=models.BooleanField(default=False, verbose_name='All Day Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 3600)),
        ),
    ]
